### ISSUE TITLE
How to run inference using images instead of a random tensor?

### ISSUE THREAD

**Issue by Tylersuard** [elcronos/COVID-19#39]
In the Model.ipynb notebook: https://github.com/elcronos/COVID-19/blob/master/notebooks/Model.ipynb

There is code to run inference on a randomized tensor but not on an actual image.  Can we change that?  I'm having trouble converting and testing it.

**Comment by elcronos** [comment]
Hi @Tylersuard that notebook can be changed. The example works with a random image because it has the same dimensions that an image. If you want to check real example of an image have a look at this: https://github.com/elcronos/COVID-19/tree/master/backend . You can run the server on your local machine and test it with the example. Which correspond to an image of an xray encoded to base64

**Comment by Tylersuard** [comment]
Thank you!
