### ISSUE TITLE
Allow multilanguage markdown

### ISSUE THREAD

**Issue by elcronos** [elcronos/COVID-19#48]
So far we have been creating individual readme.md files in different languages for the main one. However @nietzscheson found that it's possible to manage multilanguage markdown. Can any one setup  this for our repo?

https://github.com/codenautas/multilang

**Comment by diogofalken** [comment]
@elcronos I was messing around with **multilang** and I found that it just has support for **6** languages:

- Deutsch
- Spanish
- French
- Italian
- Japanese
- Russian

Since we already have a translation to **arabic** and probably many others are coming we have two chances:
- Keep accepting translations
- Just support the 6 languages above

What do you think is the best path to follow?

**Comment by elcronos** [comment]
We will keep accepting translations ! Thanks for your contribution @diogofalken . I will be closing this issue
